version: '3'
name: mailing_api
services:
  api:
    container_name: mailing_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/app/src
      - ./certificates:/app/certificates
    expose:
      - '${PORT}'
